export const COPY = {
  appTitle: 'HEIST PLANNER',
  appSubtitle: 'A GTA VI fan concept',
  tagline: 'Draw the plan. Run the heist. Share the briefing.',
  planButton: 'Plan a heist',
  resumeButton: 'Resume last plan',
  sampleButton: 'Try a sample plan',
  howItWorks: [
    { step: '1', title: 'Pick a target', desc: 'Choose your mark and assemble a crew of specialists.' },
    { step: '2', title: 'Draw the plan', desc: 'Sketch infiltration and getaway routes on the blueprint.' },
    { step: '3', title: 'Run the heist', desc: 'Watch the plan play out, then export a mission briefing.' },
  ],
  desktopNote: 'Best experienced on desktop',
  narrowScreenMessage: 'HEIST PLANNER is designed for screens 1100px or wider. Please switch to a desktop browser for the full experience.',
  disclaimer:
    'Heist Planner is an unofficial, non-commercial fan concept made for the Build with React Image Editor Challenge. Grand Theft Auto and GTA VI are trademarks of their respective owners (Take-Two Interactive / Rockstar Games). This project is not affiliated with, endorsed by, or sponsored by them.',
  location: 'Vice City, Leonida',
  confidential: 'CONFIDENTIAL',
  approved: 'APPROVED',
  compromised: 'COMPROMISED',
  vaultReached: 'Vault reached',
  exitReached: 'Exit reached — clear!',
  planIncomplete: 'Plan incomplete',
  editorLoading: 'Setting up the planning table…',
  editorError: 'Could not load the image editor. Check your internet connection.',
  editorRetry: 'Retry',
  saved: 'Plan saved',
  reset: 'Blueprint reset to clean state',
  copied: 'Copied to clipboard',
  copyFailed: 'Copy failed — use the download button instead',
  startOver: 'Start over',
  startOverConfirm: 'This will erase your current plan. Are you sure?',
  planAnother: 'Plan another heist',
  download: 'Download PNG',
  copyClipboard: 'Copy to clipboard',
  openEditor: 'Open planning table',
  continueNext: 'Continue',
  back: 'Back',
  resetBlueprint: 'Reset blueprint',
  reopenEditor: 'Edit plan',
} as const;
